const menuBtn=document.querySelector('[data-menu]'); const nav=document.querySelector('[data-nav]'); if(menuBtn){menuBtn.addEventListener('click',()=>nav.classList.toggle('open'));}
const tabs=document.querySelectorAll('[data-tab]'); const panels=document.querySelectorAll('[data-panel]'); tabs.forEach(btn=>btn.addEventListener('click',()=>{tabs.forEach(b=>b.classList.remove('active')); panels.forEach(p=>p.classList.remove('active')); btn.classList.add('active'); document.getElementById(btn.dataset.tab).classList.add('active');}));
const alerts=['Ruta Monterrey - Querétaro con 18 min de retraso','Unidad U-021 entró a patio norte','Incidencia documentada en orden OT-1049','Entrega completada con evidencia fotográfica','Alerta IA: EPP incompleto en Andén 2','Inventario visual actualizado en Rack B-14'];
const alertStream=document.getElementById('alertStream'); function pushAlert(text){if(!alertStream)return; const div=document.createElement('div'); div.className='alert'; div.textContent='• '+text; alertStream.prepend(div); while(alertStream.children.length>4)alertStream.lastChild.remove();}
alerts.slice(0,3).forEach(pushAlert); const randomBtn=document.querySelector('[data-random-alert]'); if(randomBtn){randomBtn.addEventListener('click',()=>pushAlert(alerts[Math.floor(Math.random()*alerts.length)]));}
const orders=[['OT-1048','Autotransportes Norte','En tránsito','Alta','0'],['OT-1049','Frío Express','Retrasada','Media','1'],['OT-1050','Industrial Pack','Programada','Baja','0'],['OT-1051','Logística Delta','En patio','Alta','2']];
const table=document.getElementById('ordersTable'); const apiEvent=document.getElementById('apiEvent'); function renderOrders(){if(!table)return; table.innerHTML=orders.map(o=>`<tr><td>${o[0]}</td><td>${o[1]}</td><td><span class="badge">${o[2]}</span></td><td>${o[3]}</td><td>${o[4]}</td></tr>`).join('');}
function renderApi(order){if(!apiEvent)return; apiEvent.textContent=JSON.stringify({evento:'orden_actualizada',orden_id:order[0],estado:order[2],acciones:['actualizar dashboard','crear bitácora','notificar responsable']},null,2);} renderOrders(); renderApi(orders[1]);
const addOrder=document.querySelector('[data-add-order]'); if(addOrder){addOrder.addEventListener('click',()=>{const id='OT-'+(1052+orders.length); const row=[id,'Prospecto Expo','Nueva','Alta',String(Math.floor(Math.random()*3))]; orders.unshift(row); renderOrders(); renderApi(row);});}
const timeline=document.getElementById('timeline'); const scanStatus=document.getElementById('scanStatus'); const events=['Activo escaneado en almacén','Unidad asignada a ruta','Evidencia fotográfica guardada','Incidencia cerrada por supervisor','Pallet ubicado en rack C-08']; function addScan(){if(!timeline)return; const e=events[Math.floor(Math.random()*events.length)]; const now=new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'}); const div=document.createElement('div'); div.className='time-item'; div.innerHTML=`<strong>${e}</strong><span>${now} · usuario operativo · ubicación registrada</span>`; timeline.prepend(div); scanStatus.textContent=e;} document.querySelector('[data-scan]')?.addEventListener('click',addScan); ['Orden creada','QR generado','Salida de patio'].forEach((e,i)=>{setTimeout(addScan, i*180);});
const aiEvents=['Cámara Andén 2 · EPP validado · Sin alerta','Cámara Rack B · posición ocupada · 88% confianza','Cámara Planta 1 · postura de riesgo · revisar estación','Cámara Acceso 4 · chaleco no detectado · generar alerta','Cámara Patio Norte · persona en zona restringida']; document.querySelector('[data-ai-event]')?.addEventListener('click',()=>{document.getElementById('visionLog').textContent=aiEvents[Math.floor(Math.random()*aiEvents.length)];});
const inputs=['hours','cost','errors','errorCost'].map(id=>document.getElementById(id)); const roiResult=document.getElementById('roiResult'); function calc(){const [h,c,e,ec]=inputs.map(i=>Number(i?.value||0)); const monthly=(h*c*4.33)+(e*ec*.7); if(roiResult) roiResult.textContent=monthly.toLocaleString('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});} inputs.forEach(i=>i&&i.addEventListener('input',calc)); calc();
